"""Core Pydantic data models for MatchMind multi-agent communication and telemetry."""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import uuid4
from pydantic import BaseModel, Field

from matchmind.constants import FanPersona


class PlayerInfo(BaseModel):
    """Player involved in an action."""
    id: int
    name: str
    jersey_number: Optional[int] = None
    position: Optional[str] = None


class TeamInfo(BaseModel):
    """Team details."""
    id: int
    name: str


class MatchEvent(BaseModel):
    """Normalized match event representation."""
    event_id: str = Field(default_factory=lambda: str(uuid4()))
    index: int
    period: int = 1
    timestamp: str = "00:00:00.000"
    minute: int = 0
    second: int = 0
    match_id: str

    event_type: str
    team: TeamInfo
    player: Optional[PlayerInfo] = None

    # Spatial coordinates on pitch (StatsBomb: 0-120x, 0-80y)
    start_x: Optional[float] = None
    start_y: Optional[float] = None
    end_x: Optional[float] = None
    end_y: Optional[float] = None

    outcome: Optional[str] = "Success"
    under_pressure: bool = False
    duration_seconds: float = 0.0

    # Raw or event-specific extra payload (e.g. shot freeze-frame, pass body part)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class MetricState(BaseModel):
    """Rolling match metrics state updated by the Metrics Agent."""
    match_id: str
    minute: int = 0
    home_team: str = "Home"
    away_team: str = "Away"
    score: Dict[str, int] = Field(default_factory=lambda: {"home": 0, "away": 0})

    cumulative_xg: Dict[str, float] = Field(default_factory=lambda: {"home": 0.0, "away": 0.0})
    rolling_ppda: Dict[str, float] = Field(default_factory=lambda: {"home": 11.5, "away": 11.5})
    field_tilt: float = 50.0  # Percentage for home team (0 to 100)
    possession_pct: Dict[str, float] = Field(default_factory=lambda: {"home": 50.0, "away": 50.0})

    # Tactical & Momentum indicators
    momentum_direction: str = "balanced"  # "home_dominant", "away_dominant", "balanced"
    momentum_value: float = 0.0  # -100 (Away dominant) to +100 (Home dominant)
    momentum_shift_detected: bool = False
    momentum_timeline: List[Dict[str, Any]] = Field(default_factory=list)
    current_leverage_index: float = 1.0  # 1.0 = average; > 3.0 = critical dramatic moment
    tactical_shape_home: str = "4-3-3"
    tactical_shape_away: str = "4-2-3-1"

    # Action-specific metrics for the current event
    current_action_xg: Optional[float] = None
    current_action_xt: Optional[float] = None
    current_pass_difficulty: Optional[float] = None



class NarrativeOutput(BaseModel):
    """Explainable narrative generated by Persona and Narrative Agents."""
    narrative_id: str = Field(default_factory=lambda: str(uuid4()))
    match_id: str
    event_index: int
    minute: int
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # Narrative metadata
    game_state_arc: str = "Tense Build-Up"
    leverage_index: float = 1.0
    why_it_matters_explanation: str

    # Persona specific outputs
    commentary_by_persona: Dict[FanPersona, str] = Field(default_factory=dict)

    # Multi-language translations for the primary commentary
    translations: Dict[str, str] = Field(default_factory=dict)

    # Compliance & verification
    verified_by_factcheck: bool = False
    factcheck_notes: Optional[str] = None


class AgentMessage(BaseModel):
    """Standardized message envelope for the MatchMind message bus."""
    message_id: str = Field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    source_agent: str
    target_agents: List[str] = Field(default_factory=lambda: ["*"])
    match_id: str
    event_index: int
    match_minute: int
    message_type: str  # e.g., "RAW_EVENT", "METRIC_UPDATE", "NARRATIVE_OUTPUT"
    payload: Dict[str, Any] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AgentHealth(BaseModel):
    """Agent health status for the multi-agent cluster monitoring bar."""
    agent_id: str
    role_name: str
    status: str = "healthy"  # "healthy", "processing", "degraded", "error"
    last_active: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    processed_count: int = 0
    error_count: int = 0
    average_latency_ms: float = 0.0
    current_task: Optional[str] = "Idle"

